name = "temp-email-worker"
main = "src/index.js"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "temp-email-db"
database_id = "c68a9d22-ffa2-42f8-98cc-68f5561ca7cd"

[triggers]
crons = ["0 * * * *"] # 每小时执行一次，检查并清理超过48小时的数据
